### ISSUE TITLE
Several sites in the sites.md not valid

### ISSUE THREAD

**Issue by JayEff87** [AtoraSuunva/Booru-Discord#21]
Several sites in the sites.md file do not seem to be recognized by the bot anymore. To see this error in action, attempt to blacklist dollbooru: ```b!bl site do``` which results in the error Failed to blacklist do: Unsupported site.

**Comment by AtoraSuunva** [comment]
Yeah, that was a result of me dropping dollbooru support from [booru](https://github.com/AtlasTheBot/booru) since the site just died, same applies for `youhate.us`, trying to visit the site just ends with a timeout since the server never responds. I'll push out the update to remove dollbooru/youhateus after I finish up the `booru` rewrite

**Comment by AtoraSuunva** [comment]
They've been removed https://github.com/AtlasTheBot/Booru-Discord/pull/22
